# Generated by Django 3.2 on 2022-11-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='province_id',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='country_code',
            new_name='country',
        ),
    ]
